try:
	from tkinter import *
	import random
	import os
	import tkinter.messagebox as tmsg

	os.system('del game.py')
	os.system('cls')
	root = Tk()
	root.title("Cricket Made On TK")

	# Defining Huge 
	def play():
		os.system('del game.py')
		os.system('cls')
		if (en3.get()) >6 or (en4.get()) >6 or (en5.get()) >6 or (en6.get()) >6 or (en7.get()) >6 or (en8.get()) >6 or (en9.get()) >6 or (end.get()) >100:
			tmsg.showinfo('Warning','Sorry Maximum Run Or Score Is Given')
		else:
			f = open('game.py','w+')
			f.write(f'''
from tkinter import *
import random
import time
import tkinter.messagebox as tmsg

root = Tk()
root.title('Cricket')

def rand():
	d = random.randint(0,7)

def nun():
	pass

# Defining
def rolltwo():
	btn1.config(text = "Rolling..",state=DISABLED)
	if (first.get()) >={(end.get())}:
		btn1.config(text="{(en1.get())} Won The Game",command=nun)
		root.title("{(en1.get())}'s Won The Game")
	elif (second.get()) >={(end.get())}:
		btn1.config(text="{(en2.get())} Won The Game",command=nun)
		root.title("{(en2.get())}'s Won The Game")
	else:
		for i in range(0,49):
			root.update()
			d = random.randint(0,7)
			secondt.set(d)
			time.sleep(.1)
		if (secondt.get())==1:
			btn1.config(text="Number Is 1 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 1 So... Run Is {(en3.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			secondt.set(0)
			btn1.config(text="ROLL THE DICE")
			first.set((first.get())+{(en3.get())})
		elif (secondt.get())==2:
			btn1.config(text="Number Is 2 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 2 So... Run Is {(en4.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			secondt.set(0)
			btn1.config(text="ROLL THE DICE")
			first.set((first.get())+{(en4.get())})
		elif (secondt.get())==3:
			btn1.config(text="Number Is 3 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 3 So... Run Is {(en5.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			secondt.set(0)
			btn1.config(text="ROLL THE DICE")
			first.set((first.get())+{(en5.get())})
		elif (secondt.get())==4:
			btn1.config(text="Number Is 4 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 4 So... Run Is {(en6.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			secondt.set(0)
			btn1.config(text="ROLL THE DICE")
			first.set((first.get())+{(en6.get())})
		elif (secondt.get())==5:
			btn1.config(text="Number Is 5 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 5 So... Run Is {(en7.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			secondt.set(0)
			btn1.config(text="ROLL THE DICE")
			first.set((first.get())+{(en7.get())})
		elif (secondt.get())==6:
			btn1.config(text="Number Is 6 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 6 So... Run Is {(en8.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			secondt.set(0)
			btn1.config(text="ROLL THE DICE")
			first.set((first.get())+{(en8.get())})
		elif (secondt.get())==7:
			btn1.config(text="Number Is 7 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 7 So... Run Is {(en9.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			secondt.set(0)
			btn1.config(text="ROLL THE DICE")
			first.set((first.get())+{(en9.get())})
		elif (secondt.get())==0:
			btn1.config(text="Number Is 0 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 0 So... You're Out")
			root.update()
			time.sleep(.9)
			root.update()
			secondt.set(0)
			btn1.config(text="ROLL THE DICE")
			second.set({(end.get())})
		btn1.config(text="ROLL THE DICE",state=NORMAL,command=rollone)
		root.title("{(en2.get())}'s Turn")
def rollone():
	btn1.config(text = "Rolling..",state=DISABLED)
	if (second.get()) >={(end.get())}:
		btn1.config(text="{(en2.get())} Won The Game",command=nun)
		root.title("{(en2.get())}'s Won The Game")
	elif (first.get()) >={(end.get())}:
		btn1.config(text="{(en1.get())} Won The Game",command=nun)
		root.title("{(en1.get())}'s Won The Game")
	else:
		for i in range(0,49):
			root.update()
			d = random.randint(0,7)
			firstt.set(d)
			time.sleep(.1)
		if (firstt.get())==1:
			btn1.config(text="Number Is 1 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 1 So... Run Is {(en3.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			firstt.set(0)
			btn1.config(text="ROLL THE DICE")
			second.set((second.get())+{(en3.get())})
		elif (firstt.get())==2:
			btn1.config(text="Number Is 2 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 2 So... Run Is {(en4.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			firstt.set(0)
			btn1.config(text="ROLL THE DICE")
			second.set((second.get())+{(en4.get())})
		elif (firstt.get())==3:
			btn1.config(text="Number Is 3 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 3 So... Run Is {(en5.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			firstt.set(0)
			btn1.config(text="ROLL THE DICE")
			second.set((second.get())+{(en5.get())})
		elif (firstt.get())==4:
			btn1.config(text="Number Is 4 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 4 So... Run Is {(en6.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			firstt.set(0)
			btn1.config(text="ROLL THE DICE")
			second.set((second.get())+{(en6.get())})
		elif (firstt.get())==5:
			btn1.config(text="Number Is 5 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 5 So... Run Is {(en7.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			firstt.set(0)
			btn1.config(text="ROLL THE DICE")
			second.set((second.get())+{(en7.get())})
		elif (firstt.get())==6:
			btn1.config(text="Number Is 6 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 6 So... Run Is {(en8.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			firstt.set(0)
			btn1.config(text="ROLL THE DICE")
			second.set((second.get())+{(en8.get())})
		elif (firstt.get())==7:
			btn1.config(text="Number Is 7 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 7 So... Run Is {(en9.get())}")
			root.update()
			time.sleep(.9)
			root.update()
			firstt.set(0)
			btn1.config(text="ROLL THE DICE")
			second.set((second.get())+{(en9.get())})
		elif (firstt.get())==0:
			btn1.config(text="Number Is 0 So.")
			root.update()
			time.sleep(.8)
			btn1.config(text="Number Is 0 So... You're Out")
			root.update()
			time.sleep(.9)
			root.update()
			firstt.set(0)
			btn1.config(text="ROLL THE DICE")
			first.set({(end.get())})
		btn1.config(text="ROLL THE DICE",state=NORMAL,command=rolltwo)
		root.title("{(en1.get())}'s Turn")
# Making Frames
f1 = Frame(borderwidth = 10,bg = 'black')
f2 = Frame(borderwidth = 10,bg = 'black')
f3 = Frame(borderwidth = 10,bg = 'black')
f4 = Frame(borderwidth = 10,bg = 'black')
f5 = Frame(borderwidth = 10,bg = 'black')
f6 = Frame(borderwidth = 10,bg = 'black')
f7 = Frame(borderwidth = 10,bg = 'black')
f8 = Frame(borderwidth = 10,bg = 'black')
f9 = Frame(borderwidth = 10,bg = 'black')
f10 = Frame(borderwidth = 10,bg = 'black')
f11 = Frame(borderwidth = 10,bg = 'black')

# Making Variables
first = IntVar()
second = IntVar()
first.set(0)
second.set(0)
firstt = IntVar()
secondt = IntVar()
secondt.set(0)

l1 = Label(f1, text = "Player1: {(en1.get())}",bg = "black",fg = "white",font = "comicsansms 19 bold")
l2 = Label(f1, text = "                          Player2: {(en2.get())}",bg = "black",fg = "white",font = "comicsansms 19 bold")

l1.pack(side = LEFT)
l2.pack(side = LEFT)

l3 = Label(f2, text = "SCORE: ",bg = "black",fg = "white",font = "comicsansms 17 bold")
l33 = Label(f2, textvariable = first,bg = "black",fg = "white",font = "comicsansms 17 bold")
l4 = Label(f2, text = "                                             SCORE:",bg = "black",fg = "white",font = "comicsansms 17 bold")
l44 = Label(f2, textvariable = second,bg = "black",fg = "white",font = "comicsansms 17 bold")

l3.pack(side = LEFT)
l33.pack(side = LEFT)
l4.pack(side = LEFT)
l44.pack(side= LEFT)

Label(f3,text = "Number:",bg = "black",fg = "white",font = "comicsansms 30").pack(side = LEFT)
Label(f3,textvariable = secondt,bg = "black",fg = "white",font = "comicsansms 30").pack(side = LEFT)
Label(f3,text = "              Number:",bg = "black",fg = "white",font = "comicsansms 30").pack(side = LEFT)
Label(f3,textvariable = firstt,bg = "black",fg = "white",font = "comicsansms 30").pack(side = LEFT)
Label(f3,text = "",bg = "black").pack()
Label(f3,text = "",bg = "black").pack()
Label(f3,text = "",bg = "black").pack()
Label(f3,text = "",bg = "black").pack()
Label(f3,text = "",bg = "black").pack()
Label(f3,text = "",bg = "black").pack()
Label(f3,text = "",bg = "black").pack()
Label(f3,text = "",bg = "black").pack()
Label(f3, text = "                                               ",bg = "black").pack(side = LEFT)
btn1 = Button(f3,text = "ROLL THE DICE",bg = "black",fg = "white",font = "comicsansms 17 bold",padx = 20,pady=20,command = rollone)
btn1.pack(side=LEFT)
f1.pack(anchor = "w")
f2.pack(anchor = "w")
f3.pack(anchor = "w")
f4.pack(anchor = "w")
f5.pack(anchor = "w")
f6.pack(anchor = "w")
f7.pack(anchor = "w")
f8.pack(anchor = "w")
f9.pack(anchor = "w")
f10.pack(anchor = "w")
f11.pack()

root.config(bg = "black")
root.mainloop()
		''')
			f.close()
			os.system('start game.py')
			os.system('cls')

	# Making Frames
	f1 = Frame(borderwidth = 10,bg = 'black')
	f2 = Frame(borderwidth = 10,bg = 'black')
	f3 = Frame(borderwidth = 10,bg = 'black')
	f4 = Frame(borderwidth = 10,bg = 'black')
	f5 = Frame(borderwidth = 10,bg = 'black')
	f6 = Frame(borderwidth = 10,bg = 'black')
	f7 = Frame(borderwidth = 10,bg = 'black')
	f8 = Frame(borderwidth = 10,bg = 'black')
	f9 = Frame(borderwidth = 10,bg = 'black')
	f10 = Frame(borderwidth = 10,bg = 'black')
	f11 = Frame(borderwidth = 10,bg = 'black')

	# Making Entry
	en1 = StringVar()
	en2 = StringVar()
	en3 = IntVar()
	en4 = IntVar()
	en5 = IntVar()
	en6 = IntVar()
	en7 = IntVar()
	en8 = IntVar()
	en9 = IntVar()
	en10 = IntVar()

	# Setting Entrys
	en1.set("Alex")
	en2.set("Barry")
	en3.set("6")
	en4.set("5")
	en5.set("4")
	en6.set("3")
	en7.set("2")
	en8.set("1")
	en9.set("0")
	en10.set("out")

	l1 = Label(f1, text = "Player1:",bg = "black",fg = "white",font = "comicsansms 13 bold")
	entry1 = Entry(f1, textvariable = en1,bg = "black",fg = "white",font = "comicsansms 13 bold")
	l2 = Label(f1, text = "  Player2:",bg = "black",fg = "white",font = "comicsansms 13 bold")
	entry2 = Entry(f1, textvariable = en2,bg = "black",fg = "white",font = "comicsansms 13 bold")

	l1.pack(side = LEFT)
	entry1.pack(side = LEFT)
	l2.pack(side = LEFT)
	entry2.pack(side = LEFT)

	l1 = Label(f2,text = "Numbers",bg = "black",fg = "white",font = "comicsansms 13 bold")
	l2 = Label(f2,text = "                                                                            Runs",bg = "black",fg = "white",font = "comicsansms 13 bold")
	l1.pack(side = LEFT)
	l2.pack(side = LEFT)

	l3 = Label(f3, text = "1                                                 =                                         ",bg = "black",fg = "white",font = "comicsansms 13 bold")
	entry3 = Entry(f3,textvariable = en3,bg = "white",fg = "black",font = "comicsansms 13 bold",width = 5,justify = "center")
	l3.pack(side=LEFT)
	entry3.pack(side = LEFT)

	l4 = Label(f4, text = "2                                                 =                                         ",bg = "black",fg = "white",font = "comicsansms 13 bold")
	entry4 = Entry(f4,textvariable = en4,bg = "white",fg = "black",font = "comicsansms 13 bold",width = 5,justify = "center")
	l4.pack(side=LEFT)
	entry4.pack(side = LEFT)

	l5 = Label(f5, text = "3                                                 =                                         ",bg = "black",fg = "white",font = "comicsansms 13 bold")
	entry5 = Entry(f5,textvariable = en5,bg = "white",fg = "black",font = "comicsansms 13 bold",width = 5,justify = "center")
	l5.pack(side=LEFT)
	entry5.pack(side = LEFT)

	l6 = Label(f6, text = "4                                                 =                                         ",bg = "black",fg = "white",font = "comicsansms 13 bold")
	entry6 = Entry(f6,textvariable = en6,bg = "white",fg = "black",font = "comicsansms 13 bold",width = 5,justify = "center")
	l6.pack(side=LEFT)
	entry6.pack(side = LEFT)

	l7 = Label(f7, text = "5                                                 =                                         ",bg = "black",fg = "white",font = "comicsansms 13 bold")
	entry7 = Entry(f7,textvariable = en7,bg = "white",fg = "black",font = "comicsansms 13 bold",width = 5,justify = "center")
	l7.pack(side=LEFT)
	entry7.pack(side = LEFT)

	l8 = Label(f8, text = "6                                                 =                                         ",bg = "black",fg = "white",font = "comicsansms 13 bold")
	entry8 = Entry(f8,textvariable = en8,bg = "white",fg = "black",font = "comicsansms 13 bold",width = 5,justify = "center")
	l8.pack(side=LEFT)
	entry8.pack(side = LEFT)

	l9 = Label(f9, text = "7                                                 =                                         ",bg = "black",fg = "white",font = "comicsansms 13 bold")
	entry9 = Entry(f9,textvariable = en9,bg = "white",fg = "black",font = "comicsansms 13 bold",width = 5,justify = "center")
	l9.pack(side=LEFT)
	entry9.pack(side = LEFT)

	l10 = Label(f10, text = "0                                                 =                                         ",bg = "black",fg = "white",font = "comicsansms 13 bold")
	entry10 = Entry(f10,textvariable = en10,state=DISABLED,bg = "white",fg = "black",font = "comicsansms 13 bold",width = 5,justify = "center")
	l10.pack(side=LEFT)
	entry10.pack(side = LEFT)

	end = IntVar()
	end.set(25)
	l12 = Label(f11,text="score",bg = "black",fg = "white",font = "comicsansms 13 bold",justify = "center")
	entry12 = Entry(f11,textvariable=end,bg = "black",fg = "white",font = "comicsansms 13 bold",justify = "center",width=5)
	l11 = Label(f11,text="Game Ends On: ",bg = "black",fg = "white",font = "comicsansms 13 bold",justify = "center")

	f1.pack(anchor = "w")
	f2.pack(anchor = "w")
	f3.pack(anchor = "w")
	f4.pack(anchor = "w")
	f5.pack(anchor = "w")
	f6.pack(anchor = "w")
	f7.pack(anchor = "w")
	f8.pack(anchor = "w")
	f9.pack(anchor = "w")
	f10.pack(anchor = "w")

	l11.pack(side=LEFT)
	entry12.pack(side=LEFT)
	l12.pack(side=LEFT)
	f11.pack(anchor="w")

	btn122 = Button(text="Play Game",bg = "black",fg = "white",font = "comicsansms 13 bold",justify = "center",padx=12,pady=12,command=play)
	btn122.pack()
	root.config(bg = "black")
	root.mainloop()
except:
	quit()